# This is the name of the workflow
name: VariableDemo

# When to trigger the workflow
on: [push,workflow_dispatch]
env:
 user_name: "Chaminda"
 demo_name: "Variable Demo"  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "VariableUsageJob"
  VariableUsageJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Using Workflow Variables
      run: echo Hello, $user_name! Welcome to $demo_name!!!
