name: VariableDemo

on: [push]
env:
 user_name: "Chaminda"
 demo_name: "Variable Demo"  

jobs:
 VariableUsageJob:
  runs-on: ubuntu-latest
  env:
   job_var1: "job variable value"
  steps:
  - name: Using Workflow Variables
    run: echo Hello, $user_name!
         Welcome to $demo_name!!!
         here is job var1 $job_var1
         here is step var1 $step_var1
    env: 
      step_var1: "Step Variable Value"

  - name: Set a Varaible
    run: echo 
         "::set-env name=user_name::Chandrasekara"
         "::set-env name=new_var::newvarvalue"
  
  - name: Using Variables
    run: echo Hello, $user_name!
         Welcome to $demo_name!!!
         here is job var1 $job_var1
         here is step new_var $new_var
  
