name: VariableDemo

on: [push,workflow_dispatch]
env:
 user_name: "Chaminda"
 demo_name: "Variable Demo"  

jobs:
  # This workflow contains a single job called "VariableUsageJob"
  VariableUsageJob:
    runs-on: ubuntu-latest
    steps:
    - name: Using Workflow Variables
      run: echo Hello, $user_name! Welcome to $demo_name!!!
